import Providers from "@/utils/provider";
import "./globals.css";
import Header from "./header";

export const metadata = {
  title: "Sin Moon Go",
  description: "Generated by Lee Seo Lin",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="min-h-screen">
        <Providers>
          <Header />
          <div className="min-h-full mx-80 pt-20">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
