import Providers from "@/utils/provider";
import "./globals.css";
import Header from "./header";
import dayjs from "dayjs";
import isLeapYear from "dayjs/plugin/isLeapYear"; // 윤년 판단 플러그인
import "dayjs/locale/ko"; // 한국어 가져오기

dayjs.extend(isLeapYear); // 플러그인 등록
dayjs.locale("ko"); // 언어 등록

export const metadata = {
  title: "Sin Moon Go",
  description: "Generated by Lee Seo Lin",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="min-h-screen">
        <Providers>
          <Header />
          <div className="min-h-full mx-80 pt-28">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
