import "./globals.css";
import Header from "./header";

export const metadata = {
  title: "Sin Moon Go",
  description: "Generated by Lee Seo Lin",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="min-h-screen">
        <Header />
        <div className="mx-80 min-h-full mt-20">{children}</div>
      </body>
    </html>
  );
}
